name: battery_level
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.phntm.workshop.battery_level
        pluginClass: BatteryLevelPlugin
      ios:
        pluginClass: BatteryLevelPlugin
      web:
        pluginClass: BatteryLevelWeb
        fileName: battery_level_web.dart