name: state_management_cart
description: phntm workshop about State Management

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  badges: ^2.0.1
  flutter:
    sdk: flutter
  provider: ^6.0.0
  # TODO replace with your own api package
  shopping_cart_api:
    path: shopping_cart_api

  # TODO Use one of
  # provider: ^6.0.1

  # lutter_bloc: ^8.0.0

  # flutter_state_notifier: ^0.7.1
  # state_notifier: ^0.7.1

dev_dependencies:
  # bloc_test: 9.0.1
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  network_image_mock: ^2.0.1
  test: ^1.17.0

flutter:
  uses-material-design: true
